/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 SP1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "D_aliases.h"
#include "D.h"
#include "CS_aliases.h"
#include "CS.h"
#include "LCD_WR_aliases.h"
#include "LCD_WR.h"
#include "LCD_RD_aliases.h"
#include "LCD_RD.h"
#include "LCD_RS_aliases.h"
#include "LCD_RS.h"
#include "RST_aliases.h"
#include "RST.h"
#include "OE.h"
#include "LCD.h"
#include "LCD_CLK.h"
#include "Camera.h"
#include "Camera_CLK.h"
#include "HREF_aliases.h"
#include "HREF.h"
#include "LCD_DMA_dma.h"
#include "Data_Out.h"
#include "SW_Clock.h"
#include "Buttons.h"
#include "SW.h"
#include "Camera_DMA_dma.h"
#include "Camera_B.h"
#include "Camera_G.h"
#include "Camera_VSYNC_aliases.h"
#include "Camera_VSYNC.h"
#include "Camera_SIOD_aliases.h"
#include "Camera_SIOD.h"
#include "Camera_SIOC_aliases.h"
#include "Camera_SIOC.h"
#include "Camera_I2C.h"
#include "Camera_I2C_PVT.h"
#include "Camera_end_line.h"
#include "Camera_R.h"
#include "Camera_M.h"
#include "Camera_DMA_Colours_dma.h"
#include "Camera_Threshold.h"
#include "Camera_end_line_colours.h"
#include "SW_DAC.h"
#include "SW_Comparator.h"
#include "SW_SW_1_aliases.h"
#include "SW_SW_1.h"
#include "SW_SW_3_aliases.h"
#include "SW_SW_3.h"
#include "SW_SW_2_aliases.h"
#include "SW_SW_2.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

